### ISSUE TITLE
executing after_commit callback after other model transaction

### ISSUE THREAD

**Issue by vsorlov** [magnusvk/after_commit_action#1]
The problem is that `execute_after_commit` adds a callback to current ActiveRecord model, but we can be in another ActiveRecord model transaction. In that case the callback won't be triggered.

We can fix it by adding current model to current transaction records with
`ActiveRecord::Base.connection.add_transaction_record self` in `execute_after_commit` method.

`add_transaction_record` will add a record to current transaction record event if there is already such record. That won't affect anything, because it is filtered with `unique` method after transaction.

What do you think? I can make a pull request for it.

**Comment by vsorlov** [comment]
@magnusvk ok, I'll do it when I have time

**Comment by vsorlov** [comment]
I've created a pull request

**Comment by magnusvk** [comment]
This is addressed by #5.
